#http://docs.travis-ci.com/user/gui-and-headless-browsers/
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
#https://github.com/lucab0ni/QmlForSymposium/blob/master/.travis.yml

language: python
#http://docs.travis-ci.com/user/build-configuration/
env:
  - MODE: user
  - MODE: library
  - MODE: idiot_to_genius
  - MODE: service
  

    
#  global:
#    - DISPLAY=:99.0

before_install:
  - git submodule update --init #--recursive
  # http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24
  - sleep 3	# give xvfb some time to start
  - xwininfo -root
  # Print out Ubuntu version and architecture type used in Travis
  - uname -m
  - lsb_release -a
 
before_script:
  - ls -lt SCRIPT
  
script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - chmod +x ./travis.sh
  - ./travis.sh $MODE
