#http://docs.travis-ci.com/user/gui-and-headless-browsers/
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

language: python
#env:
#  global:
#    - DISPLAY=:99.0

before_install:
  - git submodule update --init --recursive
before_script:
  - ls -lt SCRIPT
script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - chmod +x ./travis.sh
  - ./travis.sh

